project:
  type: website

website:
  title: "Single cell data science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lecture material
        menu:
          - href: intro-singlecell.qmd
            text: "Introduction to single cell data science" 
          - href: intro-bioc.qmd
            text: "Introduction to Bioconductor"
          - href: intro-granges.qmd
            text: "Introduction to GRanges"
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


